// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PadronObligados2021.Data;

namespace PadronObligados2021.Migrations
{
    [DbContext(typeof(PadronObligados2021Context))]
    [Migration("20201115090605_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PadronObligados2021.Models.EntidadFederativa", b =>
                {
                    b.Property<int>("EntidadFederativaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("EntidadFederativaId");

                    b.ToTable("EntidadesFederativas");
                });

            modelBuilder.Entity("PadronObligados2021.Models.FuncionPrincipal", b =>
                {
                    b.Property<int>("FuncionPrincipalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.HasKey("FuncionPrincipalId");

                    b.ToTable("FuncionesPrincipales");
                });

            modelBuilder.Entity("PadronObligados2021.Models.Municipio", b =>
                {
                    b.Property<int>("MunicipioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EntidadFederativaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("MunicipioId");

                    b.HasIndex("EntidadFederativaId");

                    b.ToTable("Municipios");
                });

            modelBuilder.Entity("PadronObligados2021.Models.NivelEscolar", b =>
                {
                    b.Property<string>("NivelEscolarId")
                        .HasColumnType("nvarchar(3)")
                        .HasMaxLength(3);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("NivelEscolarId");

                    b.ToTable("NivelesEscolares");
                });

            modelBuilder.Entity("PadronObligados2021.Models.RegimenMatrimonial", b =>
                {
                    b.Property<string>("RegimenMatrimonialId")
                        .HasColumnType("nvarchar(3)")
                        .HasMaxLength(3);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("RegimenMatrimonialId");

                    b.ToTable("RegimenesMatrimoniales");
                });

            modelBuilder.Entity("PadronObligados2021.Models.Sector", b =>
                {
                    b.Property<int>("SectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.HasKey("SectorId");

                    b.ToTable("Sectores");
                });

            modelBuilder.Entity("PadronObligados2021.Models.ServidorPublico", b =>
                {
                    b.Property<int>("ServidorPublicoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AmbitoPublico")
                        .HasColumnType("nvarchar(17)")
                        .HasMaxLength(17);

                    b.Property<string>("AmbitoSectorLaboral")
                        .HasColumnType("nvarchar(7)")
                        .HasMaxLength(7);

                    b.Property<string>("AreaAdscripcion")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("CURP")
                        .HasColumnType("nvarchar(18)")
                        .HasMaxLength(18);

                    b.Property<string>("CalleNombre")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("CarreraArea")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<int>("CodigoPostal")
                        .HasColumnType("int");

                    b.Property<string>("CorreoElectronico")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("DocumentoObtenido")
                        .HasColumnType("nvarchar(11)")
                        .HasMaxLength(11);

                    b.Property<string>("EmpleoCargoComision")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("EsServidorPublicoAnioAnterior")
                        .HasColumnType("nvarchar(2)")
                        .HasMaxLength(2);

                    b.Property<string>("EstatusNivelEscolaridad")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<DateTime>("FechaEgreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaObtencion")
                        .HasColumnType("datetime2");

                    b.Property<string>("FuncionPrincipalExperiencia")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("FuncionPrincipalId")
                        .HasColumnType("int");

                    b.Property<string>("Homoclave")
                        .HasColumnType("nvarchar(3)")
                        .HasMaxLength(3);

                    b.Property<string>("InstitucionEducativa")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("LocalidadNombre")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("LugarInstitucion")
                        .HasColumnType("nvarchar(16)")
                        .HasMaxLength(16);

                    b.Property<int>("MunicipioId")
                        .HasColumnType("int");

                    b.Property<string>("Nivel")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("NivelEscolarId")
                        .HasColumnType("nvarchar(3)")
                        .HasMaxLength(3);

                    b.Property<string>("NombreEntePublico")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Nombres")
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("NumeroCelular")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<int>("NumeroEmpleado")
                        .HasColumnType("int");

                    b.Property<string>("NumeroExterior")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("NumeroIdentificacionOficial")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("NumeroInterior")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("PrimerApellido")
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("RFC")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("RFCEntePublico")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("RegimenMatrimonialId")
                        .HasColumnType("nvarchar(3)")
                        .HasMaxLength(3);

                    b.Property<int>("SectorId")
                        .HasColumnType("int")
                        .HasMaxLength(10);

                    b.Property<string>("SegundoApellido")
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("SituacionPersonalId")
                        .HasColumnType("nvarchar(3)")
                        .HasMaxLength(3);

                    b.Property<string>("TelefonoOficina")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("ServidorPublicoId");

                    b.HasIndex("FuncionPrincipalId");

                    b.HasIndex("MunicipioId");

                    b.HasIndex("NivelEscolarId");

                    b.HasIndex("RegimenMatrimonialId");

                    b.HasIndex("SectorId");

                    b.HasIndex("SituacionPersonalId");

                    b.ToTable("ServidoresPublicos");
                });

            modelBuilder.Entity("PadronObligados2021.Models.SituacionPersonal", b =>
                {
                    b.Property<string>("SituacionPersonalId")
                        .HasColumnType("nvarchar(3)")
                        .HasMaxLength(3);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.HasKey("SituacionPersonalId");

                    b.ToTable("SituacionesPersonales");
                });

            modelBuilder.Entity("PadronObligados2021.Models.Municipio", b =>
                {
                    b.HasOne("PadronObligados2021.Models.EntidadFederativa", null)
                        .WithMany("Municipios")
                        .HasForeignKey("EntidadFederativaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PadronObligados2021.Models.ServidorPublico", b =>
                {
                    b.HasOne("PadronObligados2021.Models.FuncionPrincipal", "FuncionPrincipal")
                        .WithMany("Servidores")
                        .HasForeignKey("FuncionPrincipalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PadronObligados2021.Models.Municipio", "Municipio")
                        .WithMany("Servidores")
                        .HasForeignKey("MunicipioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PadronObligados2021.Models.NivelEscolar", "NivelEscolar")
                        .WithMany("Servidores")
                        .HasForeignKey("NivelEscolarId");

                    b.HasOne("PadronObligados2021.Models.RegimenMatrimonial", "RegimenMatrimonial")
                        .WithMany("Servidores")
                        .HasForeignKey("RegimenMatrimonialId");

                    b.HasOne("PadronObligados2021.Models.Sector", "Sector")
                        .WithMany("Servidores")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PadronObligados2021.Models.SituacionPersonal", "SituacionPersonal")
                        .WithMany("Servidores")
                        .HasForeignKey("SituacionPersonalId");
                });
#pragma warning restore 612, 618
        }
    }
}
